# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
    tags:
      - "*"
jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.check_step.outputs.branch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          ref: ${{ github.ref }}
      - name: Get current branch
        id: check_step
        run: |
          raw=$(git tag --sort=v:refname | tail -1)
          echo "Branch is $raw."
          echo ${{ github.ref_type }}
